version: '3.8'

services:

  backend:
    image: jjjjjk12/ojakgyo-be:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - '8080:8080'
    environment:
      - TZ=Asia/Seoul
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ojakgyo?createDatabaseIfNotExist=true&characterEncoding=UTF-8&characterSetResults=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    volumes:
      - ./data:/data
    networks:
      - ojakgyo_net

  mysql:
    image: mysql:8
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=ojakgyo
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ojakgyo_net

networks:
  ojakgyo_net:
    name: ojakgyo_net

volumes:
  mysql_data:
    name: ojakgyo_mysql_data

