name: KHUThon Publish Automizer

on:
  push:
    branches:
      - "main"

jobs:
  java-be-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Git Checkout
        uses: actions/checkout@v4
      -
        name: Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker Image Build & Push [BE]
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jjjjjk12/ojakgyo-be:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max


  deploy:
    needs:
      - java-be-build
    runs-on: ubuntu-latest
    steps:
      -
        name: SSH Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_HOST_SSH_PORT }}
          username: ${{ secrets.DEPLOY_HOST_USERNAME }}
          password: ${{ secrets.DEPLOY_HOST_PASSWORD }}
          script: |
            cd /home/ubuntu/be
            sudo docker pull jjjjjk12/ojakgyo-be:latest
            sudo docker compose down
            sudo docker compose up -d